version: '3'
services:
    db:
        image: mysql:5.7
        environment:
            MYSQL_DATABASE: tray
            MYSQL_ROOT_PASSWORD: 1234qwer
        ports:
            - "3307:3306"
    app:
        image: jesseuhul/vendas360:latest
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www/html
        depends_on:
            - db

