version: '3'
services:
    db:
        image: mysql:5.7
        environment:
            MYSQL_DATABASE: tray
            MYSQL_ROOT_PASSWORD: 1234qwer
        ports:
            - "3307:3306"
        volumes:
            - db_data:/var/lib/mysql
